### ISSUE TITLE
Add Fee Policy contracts

### ISSUE THREAD

**Issue by vectorman1** [LimeChain/hashport-contracts#30]
1. Define `IFeePolicy` interface contract which will abstract all different fee policies that will be implemented.
    - Method `feeAmount(uint256 _amount) returns (uint256)` 
2. Implement this interface for
   - `PercentageFee` (% of overall transaction amount)
   - `FlatFee` (flat token amount fee)

These contracts will be deployed on a per-user and per-asset basis which will have a specific service fee policy for porting usage. Once deployed, should be updated in the `LibFeeCalculator` user -> fee policy mapping.

The contracts' owner will be the multi-sig gnosis wallet governing the router contracts themselves. 

[User Stories](https://www.notion.so/limechain/Fee-Per-User-User-Stories-f7fc1ebd1cdc45a98c8f50b74ecc968f)

**Comment by Daniel-K-Ivanov** [comment]
> These contracts will be deployed on a per-user and per-asset basis which will have a specific service fee policy for porting usage. Once deployed, should be updated in the LibFeeCalculator user -> fee policy mapping.

I think that we should deploy 1 contract per entity (user). Deploying 1 contract per-user, per-asset will be a waste of resources. That being said, I think that we should have the interface defined as `feeAmountFor(address token, uint256 amount)`

**Comment by svetlio8** [comment]
@Daniel-K-Ivanov Do you think that we can have one contract with a mapping user - fee and the multi-sign will be able to add new addresses and their fees?

**Comment by bibitibooo1** [comment]
[Notion file](https://limechain.notion.site/limechain/MetaLock-Notes-Potentially-change-the-name-056ff5f92ce6459ba6721ab0c3c29ed4)
