### ISSUE TITLE
Update LibFeeCalculator to check for user-specific fee policies

### ISSUE THREAD

**Issue by vectorman1** [LimeChain/hashport-contracts#31]
Relevant [contract](https://github.com/LimeChain/hashport-contracts/blob/main/contracts/libraries/LibFeeCalculator.sol) 

1. Add a mapping to `FeeCalculator` for user address -> token address -> fee policy: 
    - `mapping(address => mapping(address => IFeePolicy)) feePolicies`
2. Add functions to set and remove fee policies from the mapping
    - `setFeePolicy(address _user, address _token, IFeePolicy _policy)`
    - `deleteFeePolicy(address _user, address _token, IFeePolicy _policy)`
4. In `distributeRewards(address _token, uint256 _amount)` before [L85](https://github.com/LimeChain/hashport-contracts/blob/main/contracts/libraries/LibFeeCalculator.sol#L85:L86) check the mapping for a set fee policy for the `msg.sender`. If such exists, call the policy `feeAmount()` to get the service fee. 

[User Stories](https://www.notion.so/limechain/Fee-Per-User-User-Stories-f7fc1ebd1cdc45a98c8f50b74ecc968f)

**Comment by bibitibooo1** [comment]
[Notion file](https://limechain.notion.site/limechain/MetaLock-Notes-Potentially-change-the-name-056ff5f92ce6459ba6721ab0c3c29ed4)
