### ISSUE TITLE
verify Avalanche Router on mainnet

### ISSUE THREAD

**Issue by svetlio8** [LimeChain/hashport-contracts#40]
Please verify the avalanche Router address:  `0xd8df34A071179fe8CEF910Ae0B43cdE49D611B49` on mainnet. You will need to checkout to the last commit before the deployment https://github.com/LimeChain/hashport-contracts/commit/c26ee046feafad8f8ee87c964aaec731bc51f8ed and pass the same order of the facets as in the router constructor.

**Comment by failfmi** [comment]
Already verified
